name: HabitMate CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install root dependencies
        run: npm install

      - name: Install backend dependencies
        run: npm install --prefix backend

      - name: Install frontend dependencies
        run: npm install --prefix frontend

      - name: Run backend tests
        run: npm test --prefix backend

      - name: Run frontend tests
        run: npm test --prefix frontend -- --watchAll=false

      - name: Build frontend
        run: npm run build --prefix frontend